import { Icons } from "../../assets";

export const Constants = [
  {
    id: 1,
    title: "HAVIT HV-G92 Gamepad",
    oldPrice: null,
    newPrice: 160,
    reviews: 88,
    image: Icons.WhiteSneaker,
    heartST: false,
  },
  {
    id: 2,
    title: "HAVIT HV-G92 Gamepad",
    oldPrice: null,
    newPrice: 160,
    reviews: 88,
    image: Icons.RedSneaker,
    heartST: false,
  },
  {
    id: 3,
    title: "HAVIT HV-G92 Gamepad",
    oldPrice: null,
    newPrice: 160,
    reviews: 88,
    image: Icons.BlueSneaker,
    heartST: false,
  },
  {
    id: 4,
    title: "HAVIT HV-G92 Gamepad",
    oldPrice: 1160,
    newPrice: 960,
    reviews: 75,
    image: Icons.GreenSneaker,
    heartST: false,
  },
  {
    id: 5,
    title: "HAVIT HV-G92 Gamepad",
    oldPrice: null,
    newPrice: 160,
    reviews: 88,
    image: Icons.BlueSneaker,
    heartST: false,
  },
  {
    id: 6,
    title: "HAVIT HV-G92 Gamepad",
    oldPrice: 1160,
    newPrice: 960,
    reviews: 75,
    image: Icons.GreenSneaker,
    heartST: false,
  },
  {
    id: 7,
    title: "HAVIT HV-G92 Gamepad",
    oldPrice: null,
    newPrice: 160,
    reviews: 88,
    image: Icons.RedSneaker,
    heartST: false,
  },
  {
    id: 8,
    title: "HAVIT HV-G92 Gamepad",
    oldPrice: 1160,
    newPrice: 960,
    reviews: 75,
    image: Icons.WhiteSneaker,
    heartST: false,
  },
];
