import { Icons } from "../../assets";

export const Constants = [
  {
    id: 1,
    title: "Nike ZoomX Vaporfly",
    newPrice: null,
    oldPrice: 160,
    rating: Icons.FiveStars,
    reviews: 88,
    image: "../../assets/image/SneakersWhite.png",
    heartImg: Icons.Heart,
    heartST: false,
  },
  {
    id: 2,
    title: "Puma Pro Max",
    newPrice: null,
    oldPrice: 160,
    rating: Icons.FiveStars,
    reviews: 88,
    image: "../../assets/image/SneakersRed.png",
    heartImg: Icons.Heart,
    heartST: false,
  },
  {
    id: 3,
    title: "Nike Are Max 90",
    newPrice: null,
    oldPrice: 160,
    rating: Icons.FiveStars,
    reviews: 88,
    image: "../../assets/image/SneakersBlue.png",
    heartImg: Icons.Heart,
    heartST: false,
  },
  {
    id: 4,
    title: "Nike Zoom Freak",
    newPrice: 960,
    oldPrice: 1160,
    rating: Icons.FourStars,
    reviews: 75,
    image: "../../assets/image/SneakersGreen.png",
    heartImg: Icons.Heart,
    heartST: false,
  },
  {
    id: 5,
    title: "Nike Are Max 90",
    newPrice: null,
    oldPrice: 160,
    rating: Icons.FiveStars,
    reviews: 88,
    image: "../../assets/image/SneakersBlue.png",
    heartImg: Icons.Heart,
    heartST: false,
  },
  {
    id: 6,
    title: "Nike Zoom Freak",
    newPrice: 960,
    oldPrice: 1160,
    rating: Icons.FourStars,
    reviews: 75,
    image: "../../assets/image/SneakersGreen.png",
    heartImg: Icons.Heart,
    heartST: false,
  },
  {
    id: 7,
    title: "Puma Pro Max",
    newPrice: null,
    oldPrice: 160,
    rating: Icons.FiveStars,
    reviews: 88,
    image: "../../assets/image/SneakersRed.png",
    heartImg: Icons.Heart,
    heartST: false,
  },
  {
    id: 8,
    title: "Nike ZoomX Vaporfly",
    newPrice: 960,
    oldPrice: 1160,
    rating: Icons.FourStars,
    reviews: 75,
    image: "../../assets/image/SneakersWhite.png",
    heartImg: Icons.Heart,
    heartST: false,
  },
];
